/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import { MyName as MyName } from './components/my-name/my-name';

interface HTMLMyNameElement extends MyName, HTMLElement {
}
declare var HTMLMyNameElement: {
  prototype: HTMLMyNameElement;
  new (): HTMLMyNameElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "my-name": HTMLMyNameElement;
  }
  interface ElementTagNameMap {
      "my-name": HTMLMyNameElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "my-name": JSXElements.MyNameAttributes;
      }
  }
  namespace JSXElements {
      export interface MyNameAttributes extends HTMLAttributes {
          mode?: string,
          color?: string,
        
          first?: string,
          last?: string
      }
  }
}

import { SolarPlanet as SolarPlanet } from './components/solar-planet/solar-planet';

interface HTMLSolarPlanetElement extends SolarPlanet, HTMLElement {
}
declare var HTMLSolarPlanetElement: {
  prototype: HTMLSolarPlanetElement;
  new (): HTMLSolarPlanetElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "solar-planet": HTMLSolarPlanetElement;
  }
  interface ElementTagNameMap {
      "solar-planet": HTMLSolarPlanetElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "solar-planet": JSXElements.SolarPlanetAttributes;
      }
  }
  namespace JSXElements {
      export interface SolarPlanetAttributes extends HTMLAttributes {
          mode?: string,
          color?: string,
        
          name?: string
      }
  }
}

